### PR TITLE
Added support for Linux arm64

### PR DESCRIPTION
**Pull request by xemle**
It would be nice to have html support also for Linux arm64 by default.

### CODE REVIEW

**Comment by xemle** [comment]
See also PR [gauge #2036](https://github.com/getgauge/gauge/pull/2036)

**Review by sriv — CHANGES_REQUESTED** [review]
This will also need changes to [`getArch`](https://github.com/getgauge/html-report/blob/9754556174d6a19fbd971752dc041f5af8b550bf/build/make.go#L340)

See https://github.com/getgauge/gauge/pull/1998/files#diff-8dee26221394440174ffc668d5d7e415416a3ceb38f4fa31c8c953792de9e2a9R445 for reference.

**Comment by xemle** [comment]
I hope my change matches your request. If not, let me know and I will change it.

Thank your for your time and your support.

**Review by sriv — APPROVED** [review]

**Comment by sriv** [comment]
I just realized that gauge needs a change to allow installation of `arm64` plugins, since the download URLs are defined only for x86 and x86_64. 

I have added this as part of https://github.com/getgauge/gauge/pull/2037

**Comment by xemle** [comment]
I've bumped the version and updated the github workflow. Hope that's OK...

**Comment by xemle** [comment]
Thank you for accepting the PR.

As for gauge_screenshot I realized that the release of 4.1.0 was not triggered yet - which should include the arm64 binary. Is this on purpose or can I help in some way?

Thank you very much for your time and your patience.

**Comment by xemle** [comment]
Thank you very much for releasing html-report for arm64. The reports are rendered nicely on my Raspberry PI 4 with Ubuntu 21.04

**Pull request merged**
