### PR TITLE
fix search tags, specs

### PR DESCRIPTION
**Pull request by sdvdxl**
can not search tags and spces  and I fixed this problem.

### CODE REVIEW

**Comment by zabil** [comment]
Thanks for the fix! @sdvdxl 
However, these files are generated from a theme repository.

Can you make the changes need in this file instead? https://github.com/getgauge/gauge-mango-theme/blob/8267df15a3e7fc40b1531a6639cef8052b3d5e9b/assets/js/main.js

Once that is done we build and update it here.

**Comment by sdvdxl** [comment]
@zabil I don't know which branch to use，golangTemplate？and I do not find `partials.tmpl` in the theme which is used in this project. So you can fix the problem self , may be save time.

**Comment by sdvdxl** [comment]
OK. WIth my friend's help,[fixed the problem](https://github.com/getgauge/gauge-mango-theme/pull/1) in the theme. And this project should use `golangTemplates` branch.

**Comment by zabil** [comment]
Thanks! will take a look.
Meanwhile. before we merge the code can you sign our CLA?
https://getgauge.io/cla.html

It's a one time requirement.

**Comment by sdvdxl** [comment]
@zabil done

**Comment by sriv** [comment]
@sdvdxl - thanks for the PR. I am going to favour this one over your PR to the gauge-mango-theme repository.

We have some changes coming up on gauge-mango-theme, and that may change the way you search. I hope it is ok with you if I merge this change instead. Please let me know.

**Comment by sdvdxl** [comment]
@sriv OK

**Comment by sriv** [comment]
@sdvdxl  - thanks for the contribution! Appreciate your patience too!

**Pull request merged**
