### PR TITLE
Fix code blocks from being escaped

### PR DESCRIPTION
**Pull request by andremota**
These changes fix the code blocks being escaped but also allows some html tags of being used.

Related to issue: #128

### CODE REVIEW

**Comment by apoorvam** [comment]
@andremota The PR looks good, thanks for that!

Can you rebase this with master and also add a unit test to it? We can then merge it.

**Comment by apoorvam** [comment]
@andremota Can you also sign the Gauge [CLA](http://getgauge.io/cla/index.html) so that we can merge? Thanks!

**Comment by andremota** [comment]
@apoorvam I think i've already signed the CLA 😄  ... anyway, added a test & rebased.

**Comment by BugDiver** [comment]
@andremota I don't see your entry in our CLA record. Could you please sign it again ?

**Comment by andremota** [comment]
@BugDiver Done.

```
Gauge CLA
Thank you for accepting the Gauge Contributors License Agreement. We appreciate your contributions to the Gauge community.
```

**Comment by BugDiver** [comment]
@andremota Thanks for the contribution.

**Pull request merged**
