### PR TITLE
 experimental approach for localisation of report

### PR DESCRIPTION
**Pull request by ajoecker**
For issue https://github.com/getgauge/html-report/issues/188

This is a first prototyp-ish approach for allowing to externalise the labels in the report to a property file. It is not complete and shall only be used as a basis for discussion on how to solve this.

E.g. there seems to be localisation package for golang, but I do not understand it now completely. Also it seems to add a new external dependency, so I tried to start with a pure internal approach.

Currently there must be a properties file with all labels and the localised string in the html report plugin itself. The user can then specify the env. variable `report_localisation` to match a defined properties file. Default is `en`. 

This approach would need also to provide a time format to display any time/date correctly.

Feel free to discuss the approach and/or point to better ways

### CODE REVIEW

**Comment by sriv** [comment]
Tests are failing - some tests use the default theme, some use a custom theme. So you may have to change settings accordingly.

Also, would a package like http://nicksnyder.github.io/go-i18n/ help?

**Comment by ajoecker** [comment]
i assume that tests are failing, as said, for me it is more a "could this be the right way to do so" discussion, for what I hesitated to open this as a PR.

An external package might help, though I have no overview of the impact of introducing such package

**Comment by nehashri** [comment]
@ajoecker This PR is stale for sometime. Is any help required to fix this or can we close this PR.

**Comment by ajoecker** [comment]
I think we just scrap it ...

**Pull request closed without merging**
