### PR TITLE
251 nested dir images

### PR DESCRIPTION
**Pull request by sriv**
some tests had incorrect expectations (w.r.t file path)

### CODE REVIEW

**Comment by cyberjaime45** [comment]
@sriv  I'm still getting no images for if failures that happens inside "concepts" logic

If failures happens, for a step inside any specs directory  -> works fine
If failures happens for a step inside any concepts directory -> no images

**Comment by sriv** [comment]
good catch, thanks @cyberjaime45  - working on it

**Comment by Debashis9012** [comment]
I am getting the below error:

`Error occurred while waiting for plugin process to finish.
Error : exit status 1
Unable to connect to plugin Html Report 4.0.10. rpc error: code = Unavailable desc = transport is closing`

versions:
```Gauge version: 1.0.7
Commit Hash: ed7b4fd6

Plugins
-------
html-report (4.0.10)
java (0.7.4)
js (2.3.8)```

**Comment by sriv** [comment]
@Debashis9012 - can you share a project that has this issue?

**Comment by Debashis9012** [comment]
@sriv Kindly find the attached project.
[issues251-java.zip](https://github.com/getgauge/html-report/files/4280379/issues251-java.zip)

**Comment by sriv** [comment]
hi @Debashis9012 - I am able to run your project successfully, and see the below stacktrace:

```
hi there!
# Specification Heading
  ## Vowel counts in single word	 ✔ ✘
        Failed Step: The word "gauge" has "4" vowels.
        Specification: specs/example.spec:16
        Error Message: java.lang.AssertionError: 
        Expecting:
         <4>
        to be equal to:
         <3>
        but was not.
        Stacktrace: 
        StepImplementation.verifyVowelsCountInWord(StepImplementation.java:24)
        java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        java.base/java.lang.reflect.Method.invoke(Method.java:566)
        com.thoughtworks.gauge.execution.MethodExecutor.execute(MethodExecutor.java:38)
        com.thoughtworks.gauge.execution.StepExecutionStage.executeStepMethod(StepExecutionStage.java:76)
        com.thoughtworks.gauge.execution.StepExecutionStage.executeStep(StepExecutionStage.java:69)
        com.thoughtworks.gauge.execution.StepExecutionStage.execute(StepExecutionStage.java:51)
        com.thoughtworks.gauge.execution.AbstractExecutionStage.executeNext(AbstractExecutionStage.java:24)
        com.thoughtworks.gauge.execution.HookExecutionStage.execute(HookExecutionStage.java:43)
        com.thoughtworks.gauge.execution.ExecutionPipeline.start(ExecutionPipeline.java:29)
        com.thoughtworks.gauge.processor.ExecuteStepProcessor.process(ExecuteStepProcessor.java:48)
        com.thoughtworks.gauge.RunnerServiceHandler.executeStep(RunnerServiceHandler.java:115)
        gauge.messages.RunnerGrpc$MethodHandlers.invoke(RunnerGrpc.java:1953)
        io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
        io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
        io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:817)
        io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        java.base/java.lang.Thread.run(Thread.java:834)
        
  ## Vowel counts in multiple word	 ✔ ✔

Successfully generated html-report to => /home/steam/Downloads/issues251-java/reports/html-report/index.html

Specifications:	1 executed	0 passed	1 failed	0 skipped
Scenarios:	2 executed	1 passed	1 failed	0 skipped

Total time taken: 2.258s
```

From your logs, I suspect that your html-report plugin might not be from this branch. Can you please uninstall and install html-report from this branch?

**Comment by Debashis9012** [comment]
This PR has been tested and verified.

**Pull request merged**
